### ISSUE TITLE
希望添加一个复制原始英文的选项

### ISSUE THREAD

**Issue by hitopo** [CopyPlusPlus/CopyPlusPlus#12]
有时候本身就是需要复制英文本身，又需要开启软件帮助翻译，就很不方便，希望添加一下复制原始英文的选项

**Comment by wy-luke** [comment]
ok，记下了。感谢支持！

**Comment by jizai** [comment]
+1，希望能有这个功能。可以增加一个是否复制翻译结果的选项，选中后复制的就是翻译后的文本，不选中就是原来的英文。

**Comment by wy-luke** [comment]
> +1，希望能有这个功能。可以增加一个是否复制翻译结果的选项，选中后复制的就是翻译后的文本，不选中就是原来的英文。

okok! 收到！感谢您的支持！

**Comment by jizai** [comment]
> 
> 
> > +1，希望能有这个功能。可以增加一个是否复制翻译结果的选项，选中后复制的就是翻译后的文本，不选中就是原来的英文。
> 
> okok! 收到！感谢您的支持！

我们应该感谢您才对，感谢做了个这么好的软件！

**Comment by wy-luke** [comment]
> > > +1，希望能有这个功能。可以增加一个是否复制翻译结果的选项，选中后复制的就是翻译后的文本，不选中就是原来的英文。
> > 
> > 
> > okok! 收到！感谢您的支持！
> 
> 我们应该感谢您才对，感谢做了个这么好的软件！

😁😁😁😁

**Comment by wy-luke** [comment]
下个版本实现
