### ISSUE TITLE
在Acrobat、万兴等PDF软件中复制时，软件会失效

### ISSUE THREAD

**Issue by wy-luke** [CopyPlusPlus/CopyPlusPlus#14]

**Comment by wy-luke** [comment]
使用Acrobat时，选中文本，右键，选择 **”复制时包含格式“**，而不是 **“复制”** 或直接ctrl+c，可以解决问题。

不过会产生若干个空格，绝了........我就想知道在Acrobat复制之后发生了什么☹

**建议更换PDF阅读器**，edge浏览器，Chrome，2345看图王测试可以使用。

![Snipaste_2021-06-11_21-58-49](https://user-images.githubusercontent.com/25719685/121698064-3b48d700-cb00-11eb-8dd6-e33af10d1c3a.png)

**Comment by melodyhang** [comment]
emmm，你好作者，这个bug在4.0还是没有解决吗？

**Comment by wy-luke** [comment]
> emmm，你好作者，这个bug在4.0还是没有解决吗？

我以为是解决的了，然后好像又没解决....emmmm..当我没说

下个版本我换了一种检测方式，我自己测试应该是可以了，这段时间就发布🦾

**Comment by melodyhang** [comment]
emmm，我前两天用是可以的，结果今天安装了最新的补丁后重启电脑就不行了，感谢作者，希望下个版本快快发布。😘

**Comment by wy-luke** [comment]
@melodyhang 你用的是哪个PDF软件？

**Comment by melodyhang** [comment]
> @melodyhang 你用的是哪个PDF软件？

Adobe Acrobat DC

**Comment by wy-luke** [comment]
> > @melodyhang 你用的是哪个PDF软件？
> 
> Adobe Acrobat DC

OK，了解。感谢！

**Comment by melodyhang** [comment]
> > > @melodyhang 你用的是哪个PDF软件？
> > 
> > 
> > Adobe Acrobat DC
> 
> OK，了解。感谢！

哈哈，应该感谢你，太好用了这个软件，帮大忙。已经推荐实验室小伙伴使用了。

**Comment by wy-luke** [comment]
> > > > @melodyhang 你用的是哪个PDF软件？
> > > 
> > > 
> > > Adobe Acrobat DC
> > 
> > 
> > OK，了解。感谢！
> 
> 哈哈，应该感谢你，太好用了这个软件，帮大忙。已经推荐实验室小伙伴使用了。

哈哈哈，互相感谢！🤣🤣

**Comment by wy-luke** [comment]
@melodyhang 可以尝试下 5.0 版本哈！

**Comment by melodyhang** [comment]
> @melodyhang 可以尝试下 5.0 版本哈！

OK，三克油。

**Comment by melodyhang** [comment]
> @melodyhang 可以尝试下 5.0 版本哈！
软件相当好用，已支持哈😊
