### ISSUE TITLE
下载地址在哪？

### ISSUE THREAD

**Issue by TGW555** [CopyPlusPlus/CopyPlusPlus#16]
最烦GITHUB上这一点，弄个列表出来，一大堆文件没用，安装包在哪，我就要安装包！！！！！安装包下载地址用醒目又大的字体标出来！！！！！！！！！！！玩侦探游戏呢？？？藏哪去了！！！！！！！！！++

**Comment by wy-luke** [comment]
1.ReadMe中写的很清楚，在公众号提供了网盘下载地址。
2.GitHub主要是提供源代码，下载在旁边的Release，如果不会使用GitHub，也请好好说话。
3.Release是什么，请自己谷歌，哦，百度也行。
4.你这样只会显得你自己的无知和可笑。
