### ISSUE TITLE
翻译功能问题

### ISSUE THREAD

**Issue by elfisworking** [CopyPlusPlus/CopyPlusPlus#2]
* 版本：Microsoft edge 版本 90.0.818.41 (官方内部版本) (64 位)
* 阅读文件类型：DPF文件
* 问题描述：只能翻译一行，如果句子跨行则内容缺失
问题图片:
![image](https://user-images.githubusercontent.com/37609214/115132574-15d5aa80-a034-11eb-9908-11f2537228bc.png)

**Comment by wy-luke** [comment]
收到, 我看下

**Comment by wy-luke** [comment]
可以先尝试换个PDF阅读器试试看

**Comment by elfisworking** [comment]
好的。

--------------原始邮件--------------
发件人："wy-luke ***@***.***&gt;;
发送时间：2021年4月18日(星期天) 中午11:15
收件人："CopyPlusPlus/CopyPlusPlus-NetFramework" ***@***.***&gt;;
抄送："elfisworking ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [CopyPlusPlus/CopyPlusPlus-NetFramework] 翻译功能问题 (#2)
-----------------------------------

 

 
可以先尝试换个PDF阅读器试试看

**Comment by wy-luke** [comment]
您好，问题还存在吗？我这边尝试是正常的。

![1620354993(1)](https://user-images.githubusercontent.com/25719685/117390089-1d47ef80-af20-11eb-9c6a-372490afadcf.jpg)

**Comment by oniow** [comment]
> 您好，问题还存在吗？我这边尝试是正常的。
> 
> ![1620354993(1)](https://user-images.githubusercontent.com/25719685/117390089-1d47ef80-af20-11eb-9c6a-372490afadcf.jpg)

你好，2.1版还存在翻译不全问题，换了pdf阅读器也是。就中断在复制内容里的回车处

**Comment by wy-luke** [comment]
> > 您好，问题还存在吗？我这边尝试是正常的。
> > ![1620354993(1)](https://user-images.githubusercontent.com/25719685/117390089-1d47ef80-af20-11eb-9c6a-372490afadcf.jpg)
> 
> 你好，2.1版还存在翻译不全问题，换了pdf阅读器也是。就中断在复制内容里的回车处

okok，我有时间就debug一下

**Comment by wy-luke** [comment]
以下摘自百度翻译文档:

> 3. 通用翻译API中，字符数量如何统计？
> 字符数量的统计以翻译的源语言字符长度为标准。一个汉字、一个英文字母、一个标点符号等均记为一个字符。空格、html标签等均计入在内。
> 
> 4. 单次翻译请求是否有字符数限制？
> 为保证您的使用体验，请将单次翻译文本长度限定为6000字节以内（汉字约为2000个字符）。此外，高峰时期单次请求文本过长或将导致翻译超时。您可将query分多次请求。

应该是单次字符数过多，百度翻译就只翻译了前面一段。可以尝试分多次翻译

**Comment by wy-luke** [comment]
3.0版本已经支持谷歌翻译, 可以尝试切换一下, 好像能避免这个问题了@galaxygh
