### ISSUE TITLE
Windows资源管理器预览信息版本号没有更新

### ISSUE THREAD

**Issue by ivysrono** [CopyPlusPlus/CopyPlusPlus#23]
![图片](https://user-images.githubusercontent.com/2649544/134758696-4b7cdda7-8084-4b38-8827-b2e6422cd7df.png)

**Comment by wy-luke** [comment]
😨😨😨😨我的锅，可能最后打包错了，不过问题不大，应该就这个版本号没变。感谢提醒！！！
