### ISSUE TITLE
希望能加入手动转换的功能

### ISSUE THREAD

**Issue by mobulan** [CopyPlusPlus/CopyPlusPlus#26]
监听剪切板总是时不时失效，有时候关掉重开也解决不了问题，希望能加入一个手动模式，将内容粘贴进去，输出已经去掉回车的版本

**Comment by wy-luke** [comment]
我先找找bug，优化优化看看能不能解决失效的问题

**Comment by mobulan** [comment]
希望先实现手动功能再去找bug，copytranslator也会时不时失效，当你们两个工具同时失效，并且两个软件重开也解决不了问题，但是却有没有一个手动方案的时候，明明都有着正确的算法，却都因为检测剪切板的问题不能用，真的令人绝望。工具至少保证在任何情况下的最低限度使用吧

**Comment by wy-luke** [comment]
ok，有道理！

**Comment by wy-luke** [comment]
@mobulan 是这样的，现在软件没有监听粘贴板的功能，软件失效应该就是因为翻译功能超时导致的。你把翻译功能直接关掉试试看，会不会稳定些。过几天我出个新版

**Comment by ghost** [comment]
> @mobulan 是这样的，现在软件没有监听粘贴板的功能，软件失效应该就是因为翻译功能超时导致的。你把翻译功能直接关掉试试看，会不会稳定些。过几天我出个新版

一直没有开启翻译开关, 在电脑熄屏之后唤醒会失效. 有时候正常使用也会失效.
电脑熄屏后导致的失效, 重开软件会生效. 
正常使用时的失效, 重开无效.

**Comment by wy-luke** [comment]
@NavisLab  那看来可能是因为快捷键失效，ctrl + c 的快捷键在息屏唤醒后，被系统占用，导致软件失效。我再尝试一下别的办法吧

**Comment by wy-luke** [comment]
@mobulan  可以试一下这个版本呀，加入了手动转换。
@NavisLab  试试看这个版本会不会稳定些。

用完给我反馈呀，谢谢谢！
[Copy++.zip](https://github.com/CopyPlusPlus/CopyPlusPlus/files/7811858/Copy%2B%2B.zip)

**Comment by ghost** [comment]
> @mobulan 可以试一下这个版本呀，加入了手动转换。 @NavisLab 试试看这个版本会不会稳定些。
> 
> 用完给我反馈呀，谢谢谢！ [Copy++.zip](https://github.com/CopyPlusPlus/CopyPlusPlus/files/7811858/Copy%2B%2B.zip)

试用了一下午，合并换行功能还是会失效。
电脑一直亮屏，关闭了翻译开关。

**Comment by wy-luke** [comment]
@NavisLab  还是用着用着就会失效？你使用的是划词方式，还是快捷键方式呀？

**Comment by ghost** [comment]
> @NavisLab 还是用着用着就会失效？你使用的是划词方式，还是快捷键方式呀？

这是我的软件设置选项图。
![图片](https://user-images.githubusercontent.com/53592572/148196641-d3439808-8c82-4ba3-8e96-07638200761b.png)

1，用着用着失效了。
2，使用 Ctrl+C 对文献进行复制。未开启划词开关。

**Comment by wy-luke** [comment]
@NavisLab 了解，我找找原因，感谢！！

**Comment by ghost** [comment]
> @NavisLab 了解，我找找原因，感谢！！

大神孜孜不倦的精神鼓舞人 :)

**Comment by wy-luke** [comment]
@mobulan v5.0 版本加入手动处理功能。
