### ISSUE TITLE
+功能？：基于鼠标驱动复制（、翻译）

### ISSUE THREAD

**Issue by Make-magic** [CopyPlusPlus/CopyPlusPlus#27]
暂时只能通过键盘出发复制翻译，甚至pdf软件(例如Bookxnote Pro)选中文字后提供了复制按钮，甚至用鼠标点击后仍然不能唤醒Copy + +（当然这其实很好，在不妨碍正常复制的功能下又能够让本软件的复制功能生效） ，但是可不可以考虑不怎么喜欢用键盘的场景（纯粹阅读不记笔记的时候），**直接动动鼠标就能够唤醒Copy ++功能**，比如[copy_PDF](https://github.com/upcxksorce/Copy_PDF_And_Translate/releases/tag/copy_PDF)里的那种，鼠标靠近屏幕左侧即触发这个Copy++功能？

**Comment by Make-magic** [comment]
补充一下，时不时失效

**Comment by wy-luke** [comment]
ok,收到. 感谢你的建议, 我觉得非常有用. 我有时间就动手操作.  再次感谢! 
然后时不时失效, 好像是因为翻译接口失效导致的软件整体功能失效. 关了翻译试试?

**Comment by Make-magic** [comment]
> 哦哦，原来是这么回事。关了后确实又有效了

**Comment by wy-luke** [comment]
> > 哦哦，原来是这么回事。关了后确实又有效了

😁😁

**Comment by wy-luke** [comment]
@Make-magic  你想要的功能实现了，试一下这个版本。

用完给我反馈呀，感谢感谢！！

[Copy++.zip](https://github.com/CopyPlusPlus/CopyPlusPlus/files/7811858/Copy%2B%2B.zip)

**Comment by Make-magic** [comment]
> 

嗯，3Q，我这几天用着看看

**Comment by wy-luke** [comment]
@Make-magic  v5.0 版本加入基于鼠标触发，可以试一下。另外可以看看还会不会失效
