### ISSUE TITLE
建议增加系统托盘和快捷键功能

### ISSUE THREAD

**Issue by ZacharyJia** [CopyPlusPlus/CopyPlusPlus#3]
感谢开源，简单使用了一下，挺好用。
但是发现复制代码也没格式了 🤣 建议搞个快捷键快速开关吧

**Comment by wy-luke** [comment]
托盘本来就打算做，但是临近考试，就把这个往后放了放😂😂，快捷方式我也记录下。感谢您的支持！

**Comment by wy-luke** [comment]
托盘功能实现了。快捷键还在努力中🐱‍🏍🐱‍🏍

**Comment by wy-luke** [comment]
您好, 目前实现了通过托盘图标开关软件的功能

**Comment by wy-luke** [comment]
下个版本实现快捷键功能
