### ISSUE TITLE
福昕pdf阅读器经常失效

### ISSUE THREAD

**Issue by lbj-007** [CopyPlusPlus/CopyPlusPlus#31]
这几天发现了这个问题，经常刚开始是好的，过一段时间（没到一天）就失效了，然后关闭软件再打开又好了，不知道是啥情况

**Comment by wy-luke** [comment]
对，有这个问题，应该是软件的问题。等我下个版本应该可以修复。

**Comment by wy-luke** [comment]
[Copy++.zip](https://github.com/CopyPlusPlus/CopyPlusPlus/files/7811858/Copy%2B%2B.zip)

@tianxuanzhizi  这个版本你试一下，应该是好用的。
如果好用，麻烦给我个回复，有问题也可以直接给我说，感谢！

**Comment by tianxuanzhizi** [comment]
>

**Comment by wy-luke** [comment]
@tianxuanzhizi  刚发布的版本还是会失效吗？

**Comment by lbj-007** [comment]
> @tianxuanzhizi 刚发布的版本还是会失效吗？

测试了一天，目前还没有问题，感谢作者大大！

**Comment by wy-luke** [comment]
> > @tianxuanzhizi 刚发布的版本还是会失效吗？
> 
> 测试了一天，目前还没有问题，感谢作者大大！

哇，也超感谢你！！！！有问题可以再随时联系我呀
