### ISSUE TITLE
翻译功能好像和谷歌内置pdf浏览器冲突

### ISSUE THREAD

**Issue by BobbyatGithub** [CopyPlusPlus/CopyPlusPlus#36]
如题，参数如下。翻译功能在本地的acrobat和word里使用都非常的丝滑好用，给作者点赞！但是在谷歌内置浏览器，例如谷歌学术直接跳转的pdf网页里，划文本然后CtrlCC，翻译窗没有反应。是我设置的问题吗？

![image](https://user-images.githubusercontent.com/94909523/150321942-3c16641a-8cc5-403c-926a-80b656777ac9.png)

**Comment by BobbyatGithub** [comment]
btw，这个UI实在是太可爱了，我可太喜欢了

**Comment by BobbyatGithub** [comment]
不仅是chrome的pdf功能，网页上的文字也无法使用ctrlcc翻译

**Comment by wy-luke** [comment]
> 不仅是chrome的pdf功能，网页上的文字也无法使用ctrlcc翻译

我有时间后瞅一瞅，你的软件设置的没问题

**Comment by lbj-007** [comment]
> 

我的没问题，全局ctrlcc都正常，也在用qq浏览器在线看paper

**Comment by wy-luke** [comment]
我试了下也没遇到问题😂😂😂

**Comment by BobbyatGithub** [comment]
解决了，给管理员权限运行就可以了。
