### ISSUE TITLE
如果作者愿意的话，是否能够开发linux版本和mac版本的软件呢？

### ISSUE THREAD

**Issue by Tiresiasel** [CopyPlusPlus/CopyPlusPlus#49]
非常感谢作者的付出！这款应用完全解决了论文资料整理上的痛点。但是作为一个多平台的用户，我想询问一下作者是否有开发mac和linux版本软件的计划呢？谢谢！

**Comment by wy-luke** [comment]
有的呀，在开发中呢。虽然鸽了很久，不过真的在做了！

**Comment by Tiresiasel** [comment]
> 有的呀，在开发中呢。虽然鸽了很久，不过真的在做了！

太好了，万分感谢！
