### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by sununsource** [CopyPlusPlus/CopyPlusPlus#6]
建议出个自动识别英文和中文模式，在识别到复制内容为英文的时候，只去除换行符，对于中文文献，则同时去除换行和空格。虽然现在已经能够这么使用了，但是还是需要手动切换，能否自动识别或者加个快速切换

**Comment by wy-luke** [comment]
你说的建议我会考虑. 目前单独做一个开关的目的是, 可以更灵活的使用去除空格, 如果内置判断规则的话, 可能会局操作. 另外, 快捷键功能已经在做啦.  感谢您的支持~

**Comment by wy-luke** [comment]
您好, 目前已经实现了您说的啦! 合并空格只对中文有效
