### ISSUE TITLE
API.cs is

### ISSUE THREAD

**Issue by noppe7856** [CopyPlusPlus/CopyPlusPlus#7]

**Comment by noppe7856** [comment]
I cannot get API.cs from your repository.
So I cannot build.
Could you push it ?

**Comment by wy-luke** [comment]
There is some my friends' secretkey, I can give you an empty file. You can add you key, and then it will work.

**Comment by wy-luke** [comment]
rename it to "API.cs"

[API.txt](https://github.com/CopyPlusPlus/CopyPlusPlus-NetFramework/files/6460170/API.txt)

**Comment by noppe7856** [comment]
thank you!
